# Generated by Django 5.0.6 on 2024-06-20 03:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=100)),
                ("product_type", models.CharField(max_length=150)),
                ("unitary_price", models.IntegerField()),
                ("product_brand", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                ("sale_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField()),
                ("unitary_price", models.IntegerField()),
                ("sale_date", models.DateField(default=datetime.date.today)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
